name: tp-php-objet
recipe: lamp
config:
  php: '8.2'
  database: mysql
  xdebug: 'develop,debug'
services:
  appserver:
    build:
      - composer install
    config:
      php: ./.lando.config/php.ini
  database:
    portforward: 3307