<h1>Nouveau logement</h1>

<form action="" method="post" novalidate>
    <div class="mb-3">
        <label for="pays" class="form-label">Pays</label>
        <input type="text" class="form-control" name="pays">

    </div>
    <div class="mb-3">
        <label for="adresse" class="form-label">Adresse</label>
        <input type="text" class="form-control" name="adresse">
    </div>


    <div class="mb-3">
        <label for="ville" class="form-label">Ville</label>
        <input type="text" class="form-control" name="ville">
    </div>


    <div class="mb-3">
        <label for="prix" class="form-label">Prix</label>
        <input type="text" class="form-control" name="prix">
    </div>



    <div class="mb-3">
        <label for="surface" class="form-label">Surface</label>
        <input type="text" class="form-control" name="surface">
    </div>

    <div class="mb-3">
        <label for="description" class="form-label">Description</label>
        <input type="text" class="form-control" name="description">
    </div>

    <div class="mb-3">
        <label for="couchage" class="form-label">Nombre de couchages</label>
        <input type="text" class="form-control" name="couchage">
    </div>

    <div class="mb-3">
        <label for="photo" class="form-label">Photo</label>
        <input type="text" class="form-control" name="photo">
    </div>


    <div class="mb-3">
        <label for="titre" class="form-label">Titre</label>
        <input type="text" class="form-control" name="titre">
    </div>

    <div class="mb-3">
        <label for="annonceur_id" class="form-label">Annonceur_id</label>
        <input type="text" class="form-control" name="annonceur_id">
    </div>

    <div class="mb-3">
        <label for="type_logement" class="form-label">Type_logement</label>
        <input type="text" class="form-control" name="type_logement_id">
    </div>


    <button type="submit" class="btn btn-primary bouton-voirplus">Ajouter un logement</button>
</form>
