<h1><?php echo $logement->titre ?></h1>



    <div class="card mb-3 card-detail">
        <img src="/<?php echo $logement->photo ?>" class="card-img-top img-card-detail">
        <div class="card-body">
            <h5 class="card-title">Localisation : <?php echo $logement->ville. ', ' .$logement->pays ?></h5>
            <p class="card-text">Description : <?php echo $logement->description ?></p>
            <p class="card-text">Surface : <?php echo $logement->surface ?> m&sup2;</p>
            <p class="card-text"><small class="text-muted"><?php echo $logement->prix ?> € /nuit</small></p>


            <?php if(isset($equipements) && count($equipements) > 0){ ?>
                <ul class="list-group list-group-horizontal liste-equipement">
                    <?php foreach( $equipements as $equipement ): ?>

                        <li class="list-group-item"><?php echo $equipement->libelle ?></li>

                    <?php endforeach ?>
                </ul>

            <?php } else {
               ?> <small class="text-muted me-4">Pas d'équipement répertorié</small> <?php ;
            } ?>









            <?php if ($view_data['isAuth']){ ?>
            <a href="/utilisateur/reserver/<?php echo $logement->id ?>" class="btn btn-dark bouton-voirplus">Réserver</a>
            <?php  } else {
                ?> <p> Connectez-vous pour réserver </p>

            <?php }?>
        </div>
    </div>

