<h1>Connexion</h1>

<?php if ($form_result && $form_result->hasError()) : ?>
    <div class="error">
        <?php echo $form_result->getError()[0]->getMessage() ?>
    </div>
<?php endif ?>

<form action="" method="post" novalidate>

    <div class="mb-3">
        <label for="email" class="form-label">Email</label>
        <input type="text" class="form-control" name="email">
    </div>

    <div class="mb-3">
        <label for="password" class="form-label">Password</label>
        <input type="password" class="form-control" name="password">
    </div>

    <button type="submit" class="btn btn-primary bouton-voirplus">Connexion</button>
</form>
