<!doctype html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD"
          crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Great+Vibes&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="/style/reset.css">
    <link rel="stylesheet" href="/style/style.css">

	<title><?php echo $html_title ?></title>

</head>
<body class="container">
	<header>
        <div class="center">
            <a href="/"><img class='logo' src="/img/logo.png">

            <nav>
                <?php if (!$view_data['isAuth']){ ?>
                    <button type="button" class="btn btn-dark bouton-voirplus"> <a href="/utilisateur/ajout">S'inscrire</a></button>
                    <button type="button" class="btn btn-dark bouton-voirplus"><a href="/utilisateur/connexion">Se connecter</a></button>
                <?php  } ?>

                <button type="button" class="btn btn-dark bouton-voirplus"><a href="/annonceur/ajout">Ajouter un logement</a></button>
                <button type="button" class="btn btn-dark bouton-voirplus"><a href="/annonceur/ajout">Voir mes réservations</a></button>
                <button type="button" class="btn btn-dark bouton-voirplus"><a href="/annonceur/mesannonces">Mes locations</a></button>
            </nav>
        </div>
    </header>
	<main>