<!doctype html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>Accès interdit - Ma Super app MVC</title>
</head>
<body>
	<header>
		<div>MON SUPER LOGO</div>
	</header>
	<main>
		<h1>Vous n'avez pas le droit d'afficher cette page...</h1>
		<p>Erreur code 403 - Accés interdit</p>
	</main>
	<footer>Copyright 2023 - L'IDEM Creative Art School</footer>
</body>
</html>