<!doctype html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<meta name="viewport" content="width=device-width, initial-scale=1.0">

	<title>Erreur serveur - Ma Super app MVC</title>
</head>
<body>
	<header>
		<div>MON SUPER LOGO</div>
	</header>
	<main>
		<h1>Le serveur a rencontré une erreur...</h1>
		<p>Erreur code 500 - Erreur interne du serveur</p>
	</main>
	<footer>Copyright 2023 - L'IDEM Creative Art School</footer>
</body>
</html>