<h1>Mes réservations</h1>


<?php if( count($reservation) <= 0 ): ?>
    <p> Vous n'avez pas encore de réservation</p>
<?php else: ?>


    <div class="d-flex flex-row container-card-findall">
        <?php foreach( $reservation as $re ): ?>
            <div class="card " style="width: 18rem;">
                <div class="card-body">
                    <h5 class="card-title"><?php echo $re->date_debut ?></h5>
                    <p class="card-text"> <?php echo $re->date_fin ?></p>

                </div>
            </div>


<!--            <div class="card " style="width: 18rem;">-->
<!--                <img src="--><?php //echo $logement->photo ?><!--" class="card-img-top img-car-findall">-->
<!--                <div class="card-body">-->
<!--                    <h5 class="card-title">--><?php //echo $logement->titre ?><!--</h5>-->
<!--                    <p class="card-text"> --><?php //echo $logement->description ?><!--</p>-->
<!--                    <a href="/logement/--><?php //echo $logement->id ?><!--" class="btn btn-dark bouton-voirplus">Voir plus</a>-->
<!--                </div>-->
<!--            </div>-->


        <?php endforeach ?>
    </div>


<?php endif ?>