<h1>Réserver</h1>

<form action="" method="post" novalidate>



    <div class="mb-3">
        <label for="date-arrivee" class="form-label">Date arrivée</label>
        <input type="date" class="form-control" name="datearrivee">
    </div>


    <div class="mb-3">
        <label for="date-depart" class="form-label">Date départ</label>
        <input type="date" class="form-control" name="datefin">
    </div>

<?php

//var_dump($_SESSION['USER']->id);
//
// echo $id_location; ?>



    <button type="submit" class="btn btn-dark bouton-voirplus">Réserver</button>
</form>
